This is a learning demo for numpy. most cases will be used in Didi's competition

In [10]:
import numpy as np
arry = np.array([[[1,1,2],[2,3,4]],[[1,3,4],[5,6,7]]])
print arry
print arry[:,:,1]
print arry[1]
print arry[1,1]
first_row_less_than2 = arry[:,:,2] < 2
second_row_more_than2 = arry[:,:,1] > 2
print first_row_less_than2
print second_row_more_than2
print ~second_row_more_than2
arry[first_row_less_than2 | second_row_more_than2] = -1
print arry

[[[1 1 2]
  [2 3 4]]

 [[1 3 4]
  [5 6 7]]]
[[1 3]
 [3 6]]
[[1 3 4]
 [5 6 7]]
[5 6 7]
[[False False]
 [False False]]
[[False  True]
 [ True  True]]
[[ True False]
 [False False]]
[[[ 1  1  2]
  [-1 -1 -1]]

 [[-1 -1 -1]
  [-1 -1 -1]]]


In [10]:
# numpy.append.  add columns and rows to an exist array. axis = 0 for row, axis = 1 for column
import numpy as np
#show how to append a matrix to another
a = np.array([[1,2,3],[4,5,6]])
print 'original a is '
print a
b = np.append(a,[[7,9],[9,0]],axis=1)
print 'after appended a matrix, a has added two column to become b:'
print b
#let us try set axis = 0
c = np.append(a,[[7,9,9]],axis=0)
print 'after append another row in a, here is c'
print c


original a is 
[[1 2 3]
 [4 5 6]]
after appended a matrix, a has added two column to become b:
[[1 2 3 7 9]
 [4 5 6 9 0]]
after append another row in a, here is c
[[1 2 3]
 [4 5 6]
 [7 9 9]]


In [20]:
# numpy.delete. remove colums or rows of an exist array. axis = 0 for row, axis = 1 for column
import numpy as np
a = np.array([[1,2,3,4],[5,6,7,8]])
print '\n original a is '
print a
b = np.delete(a,1,0) # 1 is for the 1st row, the count starts from 0
print '\n delete 1st row in a: '
print b

c = np.delete(a,np.s_[2:3:1],1) # remove the last column in a
print '\n delete last column in a:'
print c



 original a is 
[[1 2 3 4]
 [5 6 7 8]]

 delete 1st row in a: 
[[1 2 3 4]]

 delete last column in a:
[[1 2 4]
 [5 6 8]]


In [24]:
# add a column to the matrix according to the value in first column
import numpy as np
def func(b):
    if b == 0:
        return 255
    else:
        return -1
    
a = np.array([[0,12,3,4],[1,34,5,6],[0,43,6,7]])
b = [[func(i)] for i in a[:,0]]
print a
print b
print np.append(a,b,axis=1)

[[ 0 12  3  4]
 [ 1 34  5  6]
 [ 0 43  6  7]]
[[255], [-1], [255]]
[[  0  12   3   4 255]
 [  1  34   5   6  -1]
 [  0  43   6   7 255]]


In [37]:
#replace element is the array
a = np.ones([3,3],dtype=int)
print a
np.place(a[1],a[1]==[1],[255])
print a


b= np.array(['ab','b','c','ab','d'])
np.place(b,b=='ab',['s'])
print b
def getVal(i):
    if i=='ab':
        return 's'
    else:
        return i
    
c = [getVal(i) for i in b]
print c

[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[  1   1   1]
 [255 255 255]
 [  1   1   1]]
['sb' 'b' 'c' 'sb' 'd']
['sb', 'b', 'c', 'sb', 'd']


In [39]:
import numpy as np
a = np.genfromtxt('/Users/ford-pro2/Machine-Learning/Didi/order_sample',delimiter=None,dtype=None,names=('order_id','driver_id','passenger_id','start_district_id','dest_district_id','priceice_id','date','time'))
print a



[ ('97ebd0c6680f7c0535dbfdead6e51b4b', 'dd65fa250fca2833a3a8c16d2cf0457c', 'ed180d7daf639d936f1aeae4f7fb482f', '4725c39a5e5f4c188d382da3910b3f3f', '3e12208dd0be281c92a6ab57d9a6fb32', 24, '2016-01-01', '13:37:23')
 ('92c3ac9251cc9b5aab90b114a1e363be', 'c077e0297639edcb1df6189e8cda2c3d', '191a180f0a262aff3267775c4fac8972', '82cc4851f9e4faa4e54309f8bb73fd7c', 'b05379ac3f9b7d99370d443cfd5dcc28', 2, '2016-01-01', '09:47:54')
 ('abeefc3e2aec952468e2fd42a1649640', '86dbc1b68de435957c61b5a523854b69', '7029e813bb3de8cc73a8615e2785070c', 'fff4e8465d1e12621bc361276b6217cf', 'fff4e8465d1e12621bc361276b6217cf', 9, '2016-01-01', '18:24:02')
 ('cb31d0be64cda3cc66b46617bf49a05c', '4fadfa6eeaa694742de036dddf02b0c4', '21dc133ac68e4c07803d1c2f48988a83', '4b7f6f4e2bf237b6cc58f57142bea5c0', '4b7f6f4e2bf237b6cc58f57142bea5c0', 11, '2016-01-01', '22:13:27')
 ('139d492189ae5a933122c098f63252b3', 'NULL', '26963cc76da2d8450d8f23fc357db987', 'fc34648599753c9e74ab238e9a4a07ad', '87285a66236346350541b8815c5fae94',

In [69]:
# as i cannot find ways to replace a string in numpy array. 
#i'm trying to preprocess the txt file( replace the string i want before i read it to numpy array)
import os
import datetime
# first read cluster file to get the map of the hashed address. address hash ----- address id
cluster_file = '/Users/ford-pro2/Machine-Learning/Didi/season_1/training_data/cluster_map/cluster_map'
fp = open(cluster_file,'r')
dict={}
for i in fp.readlines():
    result = i.split()
    dict[result[0]]=result[1]



def transDriverID(c):
    if c == 'NULL':
        return '0'
    else: 
        return '1'
def transDistID(c):
    return dict[c]
def transDate(c):
    year,month,day = c.split('-')
    #print datetime.datetime(int(year), int(month), int(day)).strftime('%w')
    return c.replace('-',' ')+' ' +datetime.datetime(int(year), int(month), int(day)).strftime('%w')
def transTime(c):
    hour,minutes,seconds=c.split(':')
    return str(int(hour)*6+int(minutes)/10+1)
def reassembleLine(line):
    # original line format: 'order_hash','driver_hash','passenger_hash','start_district_hash','dest_district_hash','price','date','time'
    # new line format: order_take start_district_id dest_district_id year month day week timeslot
    new_line = ''
    result = line.split()
    new_line+=transDriverID(result[1])+' '
    new_line+=transDistID(result[3])+' '
    new_line+=transDistID(result[4])+' '
    new_line+=transDate(result[6])+' '
    new_line+=transTime(result[7])+' '
    return new_line
    
order_file = '/Users/ford-pro2/Machine-Learning/Didi/order_sample'
order_translate = '/Users/ford-pro2/Machine-Learning/Didi/order_sample_translate'

fp = open(order_file,'r')  

wp = open(order_translate,'w')

for line in fp.readlines():
    transline =  reassembleLine(line)
    wp.writelines(transline+'\n')

wp.flush()
wp.close()
fp.close()

#for line in fp.readlines():
#    contents = line.split()
#    new_line += contents
    

In [133]:
# this is a demo for pandas, I'm trying to use pandas to get data and do some statistics
import pandas as pd
import os
order_translate = '/Users/ford-pro2/Machine-Learning/Didi/output/order_translate_2016-01-01'
order_data=pd.read_csv(filepath_or_buffer = order_translate,sep=' ',index_col=False,names=['order_take', 'start_district_id', 'year', 'month', 'day', 'week', 'timeslot'])
idx = pd.DataFrame({'count' : order_data.groupby( [ 'start_district_id','order_take','timeslot','week','day'] ).size()}).reset_index()
#idx['week'] = order_data['week']
#idx['day'] = order_data['day']

weather = '/Users/ford-pro2/Machine-Learning/Didi/season_1/training_data/weather_data/weather_data_2016-01-01'
def transTime(c):
    hour,minutes,seconds=c.split(':')
    return int(hour)*6+int(minutes)/10+1
file = open(weather,'r')
weather = pd.DataFrame(columns=['timeslot','weather','temperature','pm25'],dtype=int)
i=0
for line in file.readlines():
    result = line.split()
    weather.loc[i]=[transTime(result[1]),int(result[2]),int((result[3].split('.'))[0]),int(result[4])]
    i = i+1
    
result = pd.merge(idx,weather, on='timeslot')
print idx
print weather
print result
#file = open('data.csv','w')
#file.writelines(idx.to_csv(index=False,header=False))
#file.flush()
#file.close()


       start_district_id  order_take  timeslot  week  day  count
0                      1           0         1     5    1      9
1                      1           0         2     5    1      7
2                      1           0         3     5    1     10
3                      1           0         4     5    1      5
4                      1           0         5     5    1      1
5                      1           0         6     5    1      1
6                      1           0         7     5    1      6
7                      1           0         8     5    1      2
8                      1           0         9     5    1      6
9                      1           0        10     5    1      6
10                     1           0        11     5    1      2
11                     1           0        12     5    1      3
12                     1           0        13     5    1      1
13                     1           0        14     5    1      4
14                     1 

In [130]:
# handle weather
import os
import pandas as pd
weather = '/Users/ford-pro2/Machine-Learning/Didi/season_1/training_data/weather_data/weather_data_2016-01-01'

def transTime(c):
    hour,minutes,seconds=c.split(':')
    return int(hour)*6+int(minutes)/10+1
file = open(weather,'r')
weather = pd.DataFrame(columns=['timeslot','weather','temperature','pm25'])
i=0
for line in file.readlines():
    result = line.split()
    #print result
    weather.loc[i]=[transTime(result[1]),int(result[2]),int((result[3].split('.'))[0]),int(result[4])]
    i = i+1
print weather
    

       0  1  2    3
0      1  1  4  177
1      1  1  3  177
2      2  1  3  177
3      2  1  3  177
4      3  1  3  177
5      3  1  3  177
6      4  1  3  177
7      4  1  3  177
8      5  1  3  177
9      5  1  3  177
10     6  1  3  177
11     6  1  3  177
12     7  1  3  177
13     7  1  3  177
14     8  1  3  177
15     8  1  3  177
16     9  1  3  177
17     9  1  3  177
18    10  1  3  177
19    10  1  3  177
20    11  1  3  206
21    11  1  3  206
22    12  1  3  206
23    12  1  3  206
24    13  1  3  206
25    13  1  3  206
26    14  1  3  206
27    14  1  3  206
28    15  1  3  206
29    15  1  3  206
..   ... .. ..  ...
249  130  2  8  133
250  130  2  8  133
251  131  2  8  128
252  131  2  8  128
253  132  2  8  128
254  132  2  8  128
255  133  2  8  128
256  133  2  8  128
257  134  2  8  128
258  134  2  8  128
259  135  2  8  128
260  135  2  8  128
261  136  2  8  128
262  136  2  8  128
263  137  2  8  126
264  137  2  8  126
265  138  2  8  126
266  138  2  8  126


In [135]:
#handle traffic info in supply mode only
import pandas as pd
import os

cluster_file = '/Users/ford-pro2/Machine-Learning/Didi/season_1/training_data/cluster_map/cluster_map'
fp = open(cluster_file,'r')
dict={}
for i in fp.readlines():
    result = i.split()
    dict[result[0]]=result[1]


def transDriverID(c):
    if c == 'NULL':
        return '0'
    else: 
        return '1'
def transDistID(c):
    return dict[c]
def transDate(c):
    year,month,day = c.split('-')
    #print datetime.datetime(int(year), int(month), int(day)).strftime('%w')
    return day+' ' +datetime.datetime(int(year), int(month), int(day)).strftime('%w')
def transTime(c):
    hour,minutes,seconds=c.split(':')
    return int(hour)*6+int(minutes)/10+1

traffic_file = '/Users/ford-pro2/Machine-Learning/Didi/season_1/training_data/traffic_data/traffic_data_2016-01-01'
file = open(traffic_file,'r')
traffic = pd.DataFrame(columns=['start_district_id','day','week','timeslot','first_T','second_T','third_T','fourth_T'])
i=0
for line in file.readlines():
    result = line.split()
    day,week = (transDate(result[5])).split()
    traffic.loc[i]=[int(transDistID(result[0])),int(day),int(week),transTime(result[6]),int((result[1].split(':'))[1]),int((result[2].split(':'))[1]),int((result[3].split(':'))[1]),int((result[4].split(':'))[1])]
    i = i+1
print traffic
    

      start_district_id  day  week  timeslot  first_T  second_T  third_T  \
0                  66.0  1.0   5.0     142.0    231.0      33.0     13.0   
1                  66.0  1.0   5.0      56.0    305.0      69.0     13.0   
2                  64.0  1.0   5.0     132.0    579.0      87.0     28.0   
3                  64.0  1.0   5.0      39.0    242.0      28.0     10.0   
4                  64.0  1.0   5.0       6.0    471.0      35.0     15.0   
5                  64.0  1.0   5.0      84.0    401.0      98.0     64.0   
6                   2.0  1.0   5.0     105.0    593.0     242.0     42.0   
7                   2.0  1.0   5.0      20.0    570.0      41.0     21.0   
8                   2.0  1.0   5.0      57.0    706.0     129.0     23.0   
9                  15.0  1.0   5.0      25.0     11.0       0.0      0.0   
10                 15.0  1.0   5.0      70.0     18.0       0.0      0.0   
11                  5.0  1.0   5.0     118.0    130.0      16.0      6.0   
12          

In [137]:
#get supply data from order
import os
import datetime

order_translate = '/Users/ford-pro2/Machine-Learning/Didi/output/order_translate'
order_data=pd.read_csv(filepath_or_buffer = order_translate,sep=' ',index_col=False,names=['order_take', 'start_district_id', 'year', 'month', 'day', 'week', 'timeslot'])
idx = pd.DataFrame({'count' : order_data.groupby( [ 'start_district_id','timeslot','day'] ).size()}).reset_index()
print idx

        start_district_id  timeslot  day  count
0                       1         1    1    187
1                       1         1    2     88
2                       1         1    3     70
3                       1         1    4     52
4                       1         1    5     90
5                       1         1    6     71
6                       1         1    7     64
7                       1         1    8     76
8                       1         1    9     69
9                       1         1   10     93
10                      1         1   11     84
11                      1         1   12     53
12                      1         1   13     55
13                      1         1   14     57
14                      1         1   15     77
15                      1         1   16     81
16                      1         1   17     94
17                      1         1   18     72
18                      1         1   19     77
19                      1         1   20